### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by adorjanandras** [Teaching-projects/SZE-MOSZE-2020-Git-egylet#5]
Szükségem lenne egy admin (mondjuk @hegyhati ) segítségére a github pages beállításánál. @vizvezetek videója alapján a következő beállításokat szeretném kérni: Branch: gh-pages, Folder: root.

**Comment by hegyhati** [comment]
![image](https://user-images.githubusercontent.com/13832329/95789247-7a0e5f00-0cdd-11eb-9048-7676f34836cb.png)

**Comment by adorjanandras** [comment]
Sorry, lokálisan volt csak meg, de már fent van.

**Comment by hegyhati** [comment]
done.
