### ISSUE TITLE
pushdocs.yml

### ISSUE THREAD

**Issue by adorjanandras** [Teaching-projects/SZE-MOSZE-2020-Git-egylet#6]
@vizvezetek egy kis segitseget szeretnek kerni. Azert is nem tageltelek meg a PR-ban, mert a workflow-m nem akar rendesen mukodni. Probaltam tobb kulonbozo szovegszerkesztovel is szerkeszteni, feleseleges spaceket keresni, tabokkal es kulonbozo szamu spacekkel tagolni, a vegere mar vs code-ban csinaltam, mint te a videodban es meg a behuzott segedvonalak it ugyan ott voltak es elvileg szorol szora megegyezik (a branch es a fajlneven kivul) a videoban bemutatottal. Ra tudnal nezni, mi lehet vele a problema?

**Comment by vizvezetek** [comment]
Nyomtam egy review-t. Nézd meg, és pattintsd helyre ezek után.
Hajrá! 😀
