### ISSUE TITLE
Elbiralo csapat

### ISSUE THREAD

**Issue by adorjanandras** [Teaching-projects/SZE-MOSZE-2020-Git-egylet#9]
@hegyhati lebeszeltuk a Cminusminus csapattal (tagok: @fruzsin, @kurucc és @bricsi0000000000000), hogy elbiraljak nekunk a #4-es feladat 2 branch-et. Szeretnelek megkerni teged, hogy rendeld hozza oket Triage joggal a repohoz.

**Comment by hegyhati** [comment]
done.
